### PR TITLE
Added an analog clock

### PR DESCRIPTION
**Pull request by ali-alzaiat**
Fixed issue #1

### CODE REVIEW

**Comment by adisuyash** [comment]
Thanks for helping @ali-alzaiat 
Can you also proceed with fixing the responsiveness of the website?

**Comment by ali-alzaiat** [comment]
Of course

**Comment by ali-alzaiat** [comment]
@adisuyash 
I have fixed the problem with the position of the elements, so now the clock should display correctly on both desktop and mobile devices.

**Comment by adisuyash** [comment]
> @adisuyash I have fixed the problem with the position of the elements, so now the clock should display correctly on both desktop and mobile devices.

Thank You so much @ali-alzaiat 🎉

**Pull request merged**
